# -*- coding: utf-8 -*-
"""Calculate PSNR between every fake image class 4 and real class 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QWIMQjdX2jug4KDCtX5C3iSw27tgMCkO
"""

from math import log10, sqrt
import cv2
import numpy as np
import os

from google.colab import drive
drive.mount('/content/gdrive')

def PSNR(original, to_compare_with):
    mse = np.mean((original - to_compare_with) ** 2)
    if(mse == 0):
        return 100
    max_pixel = 255.0
    psnr = 20 * log10(max_pixel / sqrt(mse))
    return psnr

directory_real_class_4 = "/content/gdrive/My Drive/Kaggle/randomly selected preprocessed/class 2/"
directory_fake = "/content/gdrive/My Drive/img_retina_Kaggle_class_4_state_of_art_GAN/9/"
psnr_averages = []
for fake_image in os.listdir(directory_fake):
  PSNR_average = 0
  i = 0
  for real_image in os.listdir(directory_real_class_4):
    img_real = cv2.imread(directory_real_class_4 + real_image)
    img_fake = cv2.imread(directory_fake + fake_image)
    img_real = cv2.resize(img_real, (128, 128))
    img_fake = cv2.resize(img_fake, (128, 128))
    PSNR_none = PSNR(img_real, img_fake)
    PSNR_average += PSNR_none
    i+=1
  PSNR_average = PSNR_average/i
  psnr_averages.append(PSNR_average)
  #print(fake_image + " " + str(PSNR_average))
print(min(psnr_averages))
print(max(psnr_averages))

directory_real_class_4 = "/content/gdrive/My Drive/Kaggle/randomly selected preprocessed/class 2/"
directory_fake = "/content/gdrive/My Drive/img_retina_Kaggle_class_4_state_of_art_GAN/19/"
psnr_averages = []
for fake_image in os.listdir(directory_fake):
  PSNR_average = 0
  i = 0
  for real_image in os.listdir(directory_real_class_4):
    img_real = cv2.imread(directory_real_class_4 + real_image)
    img_fake = cv2.imread(directory_fake + fake_image)
    img_real = cv2.resize(img_real, (128, 128))
    img_fake = cv2.resize(img_fake, (128, 128))
    PSNR_none = PSNR(img_real, img_fake)
    PSNR_average += PSNR_none
    i+=1
  PSNR_average = PSNR_average/i
  psnr_averages.append(PSNR_average)
  #print(fake_image + " " + str(PSNR_average))
print(min(psnr_averages))
print(max(psnr_averages))

directory_real_class_4 = "/content/gdrive/My Drive/Kaggle/randomly selected preprocessed/class 2/"
directory_fake = "/content/gdrive/My Drive/img_retina_Kaggle_class_4_state_of_art_GAN/29/"
psnr_averages = []
for fake_image in os.listdir(directory_fake):
  PSNR_average = 0
  i = 0
  for real_image in os.listdir(directory_real_class_4):
    img_real = cv2.imread(directory_real_class_4 + real_image)
    img_fake = cv2.imread(directory_fake + fake_image)
    img_real = cv2.resize(img_real, (128, 128))
    img_fake = cv2.resize(img_fake, (128, 128))
    PSNR_none = PSNR(img_real, img_fake)
    PSNR_average += PSNR_none
    i+=1
  PSNR_average = PSNR_average/i
  psnr_averages.append(PSNR_average)
  #print(fake_image + " " + str(PSNR_average))
print(min(psnr_averages))
print(max(psnr_averages))

directory_real_class_4 = "/content/gdrive/My Drive/Kaggle/randomly selected preprocessed/class 2/"
directory_fake = "/content/gdrive/My Drive/img_retina_Kaggle_class_4_state_of_art_GAN/39/"
psnr_averages = []
for fake_image in os.listdir(directory_fake):
  PSNR_average = 0
  i = 0
  for real_image in os.listdir(directory_real_class_4):
    img_real = cv2.imread(directory_real_class_4 + real_image)
    img_fake = cv2.imread(directory_fake + fake_image)
    img_real = cv2.resize(img_real, (128, 128))
    img_fake = cv2.resize(img_fake, (128, 128))
    PSNR_none = PSNR(img_real, img_fake)
    PSNR_average += PSNR_none
    i+=1
  PSNR_average = PSNR_average/i
  psnr_averages.append(PSNR_average)
  #print(fake_image + " " + str(PSNR_average))
print(min(psnr_averages))
print(max(psnr_averages))

directory_real_class_4 = "/content/gdrive/My Drive/Kaggle/randomly selected preprocessed/class 2/"
directory_fake = "/content/gdrive/My Drive/img_retina_Kaggle_class_4_state_of_art_GAN/49/"
psnr_averages = []
for fake_image in os.listdir(directory_fake):
  PSNR_average = 0
  i = 0
  for real_image in os.listdir(directory_real_class_4):
    img_real = cv2.imread(directory_real_class_4 + real_image)
    img_fake = cv2.imread(directory_fake + fake_image)
    img_real = cv2.resize(img_real, (128, 128))
    img_fake = cv2.resize(img_fake, (128, 128))
    PSNR_none = PSNR(img_real, img_fake)
    PSNR_average += PSNR_none
    i+=1
  PSNR_average = PSNR_average/i
  psnr_averages.append(PSNR_average)
  #print(fake_image + " " + str(PSNR_average))
print(min(psnr_averages))
print(max(psnr_averages))

directory_real_class_4 = "/content/gdrive/My Drive/Kaggle/randomly selected preprocessed/class 2/"
directory_fake = "/content/gdrive/My Drive/img_retina_Kaggle_class_4_state_of_art_GAN/59/"
psnr_averages = []
for fake_image in os.listdir(directory_fake):
  PSNR_average = 0
  i = 0
  for real_image in os.listdir(directory_real_class_4):
    img_real = cv2.imread(directory_real_class_4 + real_image)
    img_fake = cv2.imread(directory_fake + fake_image)
    img_real = cv2.resize(img_real, (128, 128))
    img_fake = cv2.resize(img_fake, (128, 128))
    PSNR_none = PSNR(img_real, img_fake)
    PSNR_average += PSNR_none
    i+=1
  PSNR_average = PSNR_average/i
  psnr_averages.append(PSNR_average)
  #print(fake_image + " " + str(PSNR_average))
print(min(psnr_averages))
print(max(psnr_averages))

directory_real_class_4 = "/content/gdrive/My Drive/Kaggle/randomly selected preprocessed/class 2/"
directory_fake = "/content/gdrive/My Drive/img_retina_Kaggle_class_4_state_of_art_GAN/69/"
psnr_averages = []
for fake_image in os.listdir(directory_fake):
  PSNR_average = 0
  i = 0
  for real_image in os.listdir(directory_real_class_4):
    img_real = cv2.imread(directory_real_class_4 + real_image)
    img_fake = cv2.imread(directory_fake + fake_image)
    img_real = cv2.resize(img_real, (128, 128))
    img_fake = cv2.resize(img_fake, (128, 128))
    PSNR_none = PSNR(img_real, img_fake)
    PSNR_average += PSNR_none
    i+=1
  PSNR_average = PSNR_average/i
  psnr_averages.append(PSNR_average)
  #print(fake_image + " " + str(PSNR_average))
print(min(psnr_averages))
print(max(psnr_averages))

directory_real_class_4 = "/content/gdrive/My Drive/Kaggle/randomly selected preprocessed/class 2/"
directory_fake = "/content/gdrive/My Drive/img_retina_Kaggle_class_4_state_of_art_GAN/79/"
psnr_averages = []
for fake_image in os.listdir(directory_fake):
  PSNR_average = 0
  i = 0
  for real_image in os.listdir(directory_real_class_4):
    img_real = cv2.imread(directory_real_class_4 + real_image)
    img_fake = cv2.imread(directory_fake + fake_image)
    img_real = cv2.resize(img_real, (128, 128))
    img_fake = cv2.resize(img_fake, (128, 128))
    PSNR_none = PSNR(img_real, img_fake)
    PSNR_average += PSNR_none
    i+=1
  PSNR_average = PSNR_average/i
  psnr_averages.append(PSNR_average)
  #print(fake_image + " " + str(PSNR_average))
print(min(psnr_averages))
print(max(psnr_averages))

directory_real_class_4 = "/content/gdrive/My Drive/Kaggle/randomly selected preprocessed/class 2/"
directory_fake = "/content/gdrive/My Drive/img_retina_Kaggle_class_4_state_of_art_GAN/89/"
psnr_averages = []
for fake_image in os.listdir(directory_fake):
  PSNR_average = 0
  i = 0
  for real_image in os.listdir(directory_real_class_4):
    img_real = cv2.imread(directory_real_class_4 + real_image)
    img_fake = cv2.imread(directory_fake + fake_image)
    img_real = cv2.resize(img_real, (128, 128))
    img_fake = cv2.resize(img_fake, (128, 128))
    PSNR_none = PSNR(img_real, img_fake)
    PSNR_average += PSNR_none
    i+=1
  PSNR_average = PSNR_average/i
  psnr_averages.append(PSNR_average)
  #print(fake_image + " " + str(PSNR_average))
print(min(psnr_averages))
print(max(psnr_averages))

directory_real_class_4 = "/content/gdrive/My Drive/Kaggle/randomly selected preprocessed/class 2/"
directory_fake = "/content/gdrive/My Drive/img_retina_Kaggle_class_4_state_of_art_GAN/99/"
psnr_averages = []
for fake_image in os.listdir(directory_fake):
  PSNR_average = 0
  i = 0
  for real_image in os.listdir(directory_real_class_4):
    img_real = cv2.imread(directory_real_class_4 + real_image)
    img_fake = cv2.imread(directory_fake + fake_image)
    img_real = cv2.resize(img_real, (128, 128))
    img_fake = cv2.resize(img_fake, (128, 128))
    PSNR_none = PSNR(img_real, img_fake)
    PSNR_average += PSNR_none
    i+=1
  PSNR_average = PSNR_average/i
  psnr_averages.append(PSNR_average)
  #print(fake_image + " " + str(PSNR_average))
print(min(psnr_averages))
print(max(psnr_averages))

directory_real_class_4 = "/content/gdrive/My Drive/Kaggle/randomly selected preprocessed/class 2/"
directory_fake = "/content/gdrive/My Drive/img_retina_Kaggle_class_4_state_of_art_GAN/109/"
psnr_averages = []
for fake_image in os.listdir(directory_fake):
  PSNR_average = 0
  i = 0
  for real_image in os.listdir(directory_real_class_4):
    img_real = cv2.imread(directory_real_class_4 + real_image)
    img_fake = cv2.imread(directory_fake + fake_image)
    img_real = cv2.resize(img_real, (128, 128))
    img_fake = cv2.resize(img_fake, (128, 128))
    PSNR_none = PSNR(img_real, img_fake)
    PSNR_average += PSNR_none
    i+=1
  PSNR_average = PSNR_average/i
  psnr_averages.append(PSNR_average)
  #print(fake_image + " " + str(PSNR_average))
print(min(psnr_averages))
print(max(psnr_averages))

directory_real_class_4 = "/content/gdrive/My Drive/Kaggle/randomly selected preprocessed/class 2/"
directory_fake = "/content/gdrive/My Drive/img_retina_Kaggle_class_4_state_of_art_GAN/119/"
psnr_averages = []
for fake_image in os.listdir(directory_fake):
  PSNR_average = 0
  i = 0
  for real_image in os.listdir(directory_real_class_4):
    img_real = cv2.imread(directory_real_class_4 + real_image)
    img_fake = cv2.imread(directory_fake + fake_image)
    img_real = cv2.resize(img_real, (128, 128))
    img_fake = cv2.resize(img_fake, (128, 128))
    PSNR_none = PSNR(img_real, img_fake)
    PSNR_average += PSNR_none
    i+=1
  PSNR_average = PSNR_average/i
  psnr_averages.append(PSNR_average)
  #print(fake_image + " " + str(PSNR_average))
print(min(psnr_averages))
print(max(psnr_averages))

directory_real_class_4 = "/content/gdrive/My Drive/Kaggle/randomly selected preprocessed/class 2/"
directory_fake = "/content/gdrive/My Drive/img_retina_Kaggle_class_4_state_of_art_GAN/129/"
psnr_averages = []
for fake_image in os.listdir(directory_fake):
  PSNR_average = 0
  i = 0
  for real_image in os.listdir(directory_real_class_4):
    img_real = cv2.imread(directory_real_class_4 + real_image)
    img_fake = cv2.imread(directory_fake + fake_image)
    img_real = cv2.resize(img_real, (128, 128))
    img_fake = cv2.resize(img_fake, (128, 128))
    PSNR_none = PSNR(img_real, img_fake)
    PSNR_average += PSNR_none
    i+=1
  PSNR_average = PSNR_average/i
  psnr_averages.append(PSNR_average)
  #print(fake_image + " " + str(PSNR_average))
print(min(psnr_averages))
print(max(psnr_averages))

directory_real_class_4 = "/content/gdrive/My Drive/Kaggle/randomly selected preprocessed/class 2/"
directory_fake = "/content/gdrive/My Drive/img_retina_Kaggle_class_4_state_of_art_GAN/139/"
psnr_averages = []
for fake_image in os.listdir(directory_fake):
  PSNR_average = 0
  i = 0
  for real_image in os.listdir(directory_real_class_4):
    img_real = cv2.imread(directory_real_class_4 + real_image)
    img_fake = cv2.imread(directory_fake + fake_image)
    img_real = cv2.resize(img_real, (128, 128))
    img_fake = cv2.resize(img_fake, (128, 128))
    PSNR_none = PSNR(img_real, img_fake)
    PSNR_average += PSNR_none
    i+=1
  PSNR_average = PSNR_average/i
  psnr_averages.append(PSNR_average)
  #print(fake_image + " " + str(PSNR_average))
print(min(psnr_averages))
print(max(psnr_averages))

directory_real_class_4 = "/content/gdrive/My Drive/Kaggle/randomly selected preprocessed/class 2/"
directory_fake = "/content/gdrive/My Drive/img_retina_Kaggle_class_4_state_of_art_GAN/149/"
psnr_averages = []
for fake_image in os.listdir(directory_fake):
  PSNR_average = 0
  i = 0
  for real_image in os.listdir(directory_real_class_4):
    img_real = cv2.imread(directory_real_class_4 + real_image)
    img_fake = cv2.imread(directory_fake + fake_image)
    img_real = cv2.resize(img_real, (128, 128))
    img_fake = cv2.resize(img_fake, (128, 128))
    PSNR_none = PSNR(img_real, img_fake)
    PSNR_average += PSNR_none
    i+=1
  PSNR_average = PSNR_average/i
  psnr_averages.append(PSNR_average)
  #print(fake_image + " " + str(PSNR_average))
print(min(psnr_averages))
print(max(psnr_averages))

directory_real_class_4 = "/content/gdrive/My Drive/Kaggle/randomly selected preprocessed/class 2/"
directory_fake = "/content/gdrive/My Drive/img_retina_Kaggle_class_4_state_of_art_GAN/159/"
psnr_averages = []
for fake_image in os.listdir(directory_fake):
  PSNR_average = 0
  i = 0
  for real_image in os.listdir(directory_real_class_4):
    img_real = cv2.imread(directory_real_class_4 + real_image)
    img_fake = cv2.imread(directory_fake + fake_image)
    img_real = cv2.resize(img_real, (128, 128))
    img_fake = cv2.resize(img_fake, (128, 128))
    PSNR_none = PSNR(img_real, img_fake)
    PSNR_average += PSNR_none
    i+=1
  PSNR_average = PSNR_average/i
  psnr_averages.append(PSNR_average)
  #print(fake_image + " " + str(PSNR_average))
print(min(psnr_averages))
print(max(psnr_averages))

directory_real_class_4 = "/content/gdrive/My Drive/Kaggle/randomly selected preprocessed/class 2/"
directory_fake = "/content/gdrive/My Drive/img_retina_Kaggle_class_4_state_of_art_GAN/169/"
psnr_averages = []
for fake_image in os.listdir(directory_fake):
  PSNR_average = 0
  i = 0
  for real_image in os.listdir(directory_real_class_4):
    img_real = cv2.imread(directory_real_class_4 + real_image)
    img_fake = cv2.imread(directory_fake + fake_image)
    img_real = cv2.resize(img_real, (128, 128))
    img_fake = cv2.resize(img_fake, (128, 128))
    PSNR_none = PSNR(img_real, img_fake)
    PSNR_average += PSNR_none
    i+=1
  PSNR_average = PSNR_average/i
  psnr_averages.append(PSNR_average)
  #print(fake_image + " " + str(PSNR_average))
print(min(psnr_averages))
print(max(psnr_averages))

directory_real_class_4 = "/content/gdrive/My Drive/Kaggle/randomly selected preprocessed/class 2/"
directory_fake = "/content/gdrive/My Drive/img_retina_Kaggle_class_4_state_of_art_GAN/179/"
psnr_averages = []
for fake_image in os.listdir(directory_fake):
  PSNR_average = 0
  i = 0
  for real_image in os.listdir(directory_real_class_4):
    img_real = cv2.imread(directory_real_class_4 + real_image)
    img_fake = cv2.imread(directory_fake + fake_image)
    img_real = cv2.resize(img_real, (128, 128))
    img_fake = cv2.resize(img_fake, (128, 128))
    PSNR_none = PSNR(img_real, img_fake)
    PSNR_average += PSNR_none
    i+=1
  PSNR_average = PSNR_average/i
  psnr_averages.append(PSNR_average)
  #print(fake_image + " " + str(PSNR_average))
print(min(psnr_averages))
print(max(psnr_averages))

directory_real_class_4 = "/content/gdrive/My Drive/Kaggle/randomly selected preprocessed/class 2/"
directory_fake = "/content/gdrive/My Drive/img_retina_Kaggle_class_4_state_of_art_GAN/189/"
psnr_averages = []
for fake_image in os.listdir(directory_fake):
  PSNR_average = 0
  i = 0
  for real_image in os.listdir(directory_real_class_4):
    img_real = cv2.imread(directory_real_class_4 + real_image)
    img_fake = cv2.imread(directory_fake + fake_image)
    img_real = cv2.resize(img_real, (128, 128))
    img_fake = cv2.resize(img_fake, (128, 128))
    PSNR_none = PSNR(img_real, img_fake)
    PSNR_average += PSNR_none
    i+=1
  PSNR_average = PSNR_average/i
  psnr_averages.append(PSNR_average)
  #print(fake_image + " " + str(PSNR_average))
print(min(psnr_averages))
print(max(psnr_averages))

directory_real_class_4 = "/content/gdrive/My Drive/Kaggle/randomly selected preprocessed/class 2/"
directory_fake = "/content/gdrive/My Drive/img_retina_Kaggle_class_4_state_of_art_GAN/199/"
psnr_averages = []
for fake_image in os.listdir(directory_fake):
  PSNR_average = 0
  i = 0
  for real_image in os.listdir(directory_real_class_4):
    img_real = cv2.imread(directory_real_class_4 + real_image)
    img_fake = cv2.imread(directory_fake + fake_image)
    img_real = cv2.resize(img_real, (128, 128))
    img_fake = cv2.resize(img_fake, (128, 128))
    PSNR_none = PSNR(img_real, img_fake)
    PSNR_average += PSNR_none
    i+=1
  PSNR_average = PSNR_average/i
  psnr_averages.append(PSNR_average)
  #print(fake_image + " " + str(PSNR_average))
print(min(psnr_averages))
print(max(psnr_averages))

directory_real_class_4 = "/content/gdrive/My Drive/Kaggle/randomly selected preprocessed/class 2/"
directory_fake = "/content/gdrive/My Drive/img_retina_Kaggle_class_4_state_of_art_GAN/209/"
psnr_averages = []
for fake_image in os.listdir(directory_fake):
  PSNR_average = 0
  i = 0
  for real_image in os.listdir(directory_real_class_4):
    img_real = cv2.imread(directory_real_class_4 + real_image)
    img_fake = cv2.imread(directory_fake + fake_image)
    img_real = cv2.resize(img_real, (128, 128))
    img_fake = cv2.resize(img_fake, (128, 128))
    PSNR_none = PSNR(img_real, img_fake)
    PSNR_average += PSNR_none
    i+=1
  PSNR_average = PSNR_average/i
  psnr_averages.append(PSNR_average)
  #print(fake_image + " " + str(PSNR_average))
print(min(psnr_averages))
print(max(psnr_averages))

directory_real_class_4 = "/content/gdrive/My Drive/Kaggle/randomly selected preprocessed/class 2/"
directory_fake = "/content/gdrive/My Drive/img_retina_Kaggle_class_4_state_of_art_GAN/219/"
psnr_averages = []
for fake_image in os.listdir(directory_fake):
  PSNR_average = 0
  i = 0
  for real_image in os.listdir(directory_real_class_4):
    img_real = cv2.imread(directory_real_class_4 + real_image)
    img_fake = cv2.imread(directory_fake + fake_image)
    img_real = cv2.resize(img_real, (128, 128))
    img_fake = cv2.resize(img_fake, (128, 128))
    PSNR_none = PSNR(img_real, img_fake)
    PSNR_average += PSNR_none
    i+=1
  PSNR_average = PSNR_average/i
  psnr_averages.append(PSNR_average)
  #print(fake_image + " " + str(PSNR_average))
print(min(psnr_averages))
print(max(psnr_averages))

directory_real_class_4 = "/content/gdrive/My Drive/Kaggle/randomly selected preprocessed/class 2/"
directory_fake = "/content/gdrive/My Drive/img_retina_Kaggle_class_4_state_of_art_GAN/229/"
psnr_averages = []
for fake_image in os.listdir(directory_fake):
  PSNR_average = 0
  i = 0
  for real_image in os.listdir(directory_real_class_4):
    img_real = cv2.imread(directory_real_class_4 + real_image)
    img_fake = cv2.imread(directory_fake + fake_image)
    img_real = cv2.resize(img_real, (128, 128))
    img_fake = cv2.resize(img_fake, (128, 128))
    PSNR_none = PSNR(img_real, img_fake)
    PSNR_average += PSNR_none
    i+=1
  PSNR_average = PSNR_average/i
  psnr_averages.append(PSNR_average)
  #print(fake_image + " " + str(PSNR_average))
print(min(psnr_averages))
print(max(psnr_averages))

directory_real_class_4 = "/content/gdrive/My Drive/Kaggle/randomly selected preprocessed/class 2/"
directory_fake = "/content/gdrive/My Drive/img_retina_Kaggle_class_4_state_of_art_GAN/239/"
psnr_averages = []
for fake_image in os.listdir(directory_fake):
  PSNR_average = 0
  i = 0
  for real_image in os.listdir(directory_real_class_4):
    img_real = cv2.imread(directory_real_class_4 + real_image)
    img_fake = cv2.imread(directory_fake + fake_image)
    img_real = cv2.resize(img_real, (128, 128))
    img_fake = cv2.resize(img_fake, (128, 128))
    PSNR_none = PSNR(img_real, img_fake)
    PSNR_average += PSNR_none
    i+=1
  PSNR_average = PSNR_average/i
  psnr_averages.append(PSNR_average)
  #print(fake_image + " " + str(PSNR_average))
print(min(psnr_averages))
print(max(psnr_averages))

directory_real_class_4 = "/content/gdrive/My Drive/Kaggle/randomly selected preprocessed/class 2/"
directory_fake = "/content/gdrive/My Drive/img_retina_Kaggle_class_4_state_of_art_GAN/249/"
psnr_averages = []
for fake_image in os.listdir(directory_fake):
  PSNR_average = 0
  i = 0
  for real_image in os.listdir(directory_real_class_4):
    img_real = cv2.imread(directory_real_class_4 + real_image)
    img_fake = cv2.imread(directory_fake + fake_image)
    img_real = cv2.resize(img_real, (128, 128))
    img_fake = cv2.resize(img_fake, (128, 128))
    PSNR_none = PSNR(img_real, img_fake)
    PSNR_average += PSNR_none
    i+=1
  PSNR_average = PSNR_average/i
  psnr_averages.append(PSNR_average)
  #print(fake_image + " " + str(PSNR_average))
print(min(psnr_averages))
print(max(psnr_averages))

directory_real_class_4 = "/content/gdrive/My Drive/Kaggle/randomly selected preprocessed/class 2/"
directory_fake = "/content/gdrive/My Drive/img_retina_Kaggle_class_4_state_of_art_GAN/259/"
psnr_averages = []
for fake_image in os.listdir(directory_fake):
  PSNR_average = 0
  i = 0
  for real_image in os.listdir(directory_real_class_4):
    img_real = cv2.imread(directory_real_class_4 + real_image)
    img_fake = cv2.imread(directory_fake + fake_image)
    img_real = cv2.resize(img_real, (128, 128))
    img_fake = cv2.resize(img_fake, (128, 128))
    PSNR_none = PSNR(img_real, img_fake)
    PSNR_average += PSNR_none
    i+=1
  PSNR_average = PSNR_average/i
  psnr_averages.append(PSNR_average)
  #print(fake_image + " " + str(PSNR_average))
print(min(psnr_averages))
print(max(psnr_averages))

directory_real_class_4 = "/content/gdrive/My Drive/Kaggle/randomly selected preprocessed/class 2/"
directory_fake = "/content/gdrive/My Drive/img_retina_Kaggle_class_4_state_of_art_GAN/269/"
psnr_averages = []
for fake_image in os.listdir(directory_fake):
  PSNR_average = 0
  i = 0
  for real_image in os.listdir(directory_real_class_4):
    img_real = cv2.imread(directory_real_class_4 + real_image)
    img_fake = cv2.imread(directory_fake + fake_image)
    img_real = cv2.resize(img_real, (128, 128))
    img_fake = cv2.resize(img_fake, (128, 128))
    PSNR_none = PSNR(img_real, img_fake)
    PSNR_average += PSNR_none
    i+=1
  PSNR_average = PSNR_average/i
  psnr_averages.append(PSNR_average)
  #print(fake_image + " " + str(PSNR_average))
print(min(psnr_averages))
print(max(psnr_averages))

directory_real_class_4 = "/content/gdrive/My Drive/Kaggle/randomly selected preprocessed/class 2/"
directory_fake = "/content/gdrive/My Drive/img_retina_Kaggle_class_4_state_of_art_GAN/279/"
psnr_averages = []
for fake_image in os.listdir(directory_fake):
  PSNR_average = 0
  i = 0
  for real_image in os.listdir(directory_real_class_4):
    img_real = cv2.imread(directory_real_class_4 + real_image)
    img_fake = cv2.imread(directory_fake + fake_image)
    img_real = cv2.resize(img_real, (128, 128))
    img_fake = cv2.resize(img_fake, (128, 128))
    PSNR_none = PSNR(img_real, img_fake)
    PSNR_average += PSNR_none
    i+=1
  PSNR_average = PSNR_average/i
  psnr_averages.append(PSNR_average)
  #print(fake_image + " " + str(PSNR_average))
print(min(psnr_averages))
print(max(psnr_averages))

directory_real_class_4 = "/content/gdrive/My Drive/Kaggle/randomly selected preprocessed/class 2/"
directory_fake = "/content/gdrive/My Drive/img_retina_Kaggle_class_4_state_of_art_GAN/289/"
psnr_averages = []
for fake_image in os.listdir(directory_fake):
  PSNR_average = 0
  i = 0
  for real_image in os.listdir(directory_real_class_4):
    img_real = cv2.imread(directory_real_class_4 + real_image)
    img_fake = cv2.imread(directory_fake + fake_image)
    img_real = cv2.resize(img_real, (128, 128))
    img_fake = cv2.resize(img_fake, (128, 128))
    PSNR_none = PSNR(img_real, img_fake)
    PSNR_average += PSNR_none
    i+=1
  PSNR_average = PSNR_average/i
  psnr_averages.append(PSNR_average)
  #print(fake_image + " " + str(PSNR_average))
print(min(psnr_averages))
print(max(psnr_averages))

directory_real_class_4 = "/content/gdrive/My Drive/Kaggle/randomly selected preprocessed/class 2/"
directory_fake = "/content/gdrive/My Drive/img_retina_Kaggle_class_4_state_of_art_GAN/299/"
psnr_averages = []
for fake_image in os.listdir(directory_fake):
  PSNR_average = 0
  i = 0
  for real_image in os.listdir(directory_real_class_4):
    img_real = cv2.imread(directory_real_class_4 + real_image)
    img_fake = cv2.imread(directory_fake + fake_image)
    img_real = cv2.resize(img_real, (128, 128))
    img_fake = cv2.resize(img_fake, (128, 128))
    PSNR_none = PSNR(img_real, img_fake)
    PSNR_average += PSNR_none
    i+=1
  PSNR_average = PSNR_average/i
  psnr_averages.append(PSNR_average)
  #print(fake_image + " " + str(PSNR_average))
print(min(psnr_averages))
print(max(psnr_averages))

directory_real_class_4 = "/content/gdrive/My Drive/Kaggle/randomly selected preprocessed/class 2/"
directory_fake = "/content/gdrive/My Drive/img_retina_Kaggle_class_4_state_of_art_GAN/309/"
psnr_averages = []
for fake_image in os.listdir(directory_fake):
  PSNR_average = 0
  i = 0
  for real_image in os.listdir(directory_real_class_4):
    img_real = cv2.imread(directory_real_class_4 + real_image)
    img_fake = cv2.imread(directory_fake + fake_image)
    img_real = cv2.resize(img_real, (128, 128))
    img_fake = cv2.resize(img_fake, (128, 128))
    PSNR_none = PSNR(img_real, img_fake)
    PSNR_average += PSNR_none
    i+=1
  PSNR_average = PSNR_average/i
  psnr_averages.append(PSNR_average)
  #print(fake_image + " " + str(PSNR_average))
print(min(psnr_averages))
print(max(psnr_averages))

directory_real_class_4 = "/content/gdrive/My Drive/Kaggle/randomly selected preprocessed/class 2/"
directory_fake = "/content/gdrive/My Drive/img_retina_Kaggle_class_4_state_of_art_GAN/319/"
psnr_averages = []
for fake_image in os.listdir(directory_fake):
  PSNR_average = 0
  i = 0
  for real_image in os.listdir(directory_real_class_4):
    img_real = cv2.imread(directory_real_class_4 + real_image)
    img_fake = cv2.imread(directory_fake + fake_image)
    img_real = cv2.resize(img_real, (128, 128))
    img_fake = cv2.resize(img_fake, (128, 128))
    PSNR_none = PSNR(img_real, img_fake)
    PSNR_average += PSNR_none
    i+=1
  PSNR_average = PSNR_average/i
  psnr_averages.append(PSNR_average)
  #print(fake_image + " " + str(PSNR_average))
print(min(psnr_averages))
print(max(psnr_averages))

directory_real_class_4 = "/content/gdrive/My Drive/Kaggle/randomly selected preprocessed/class 2/"
directory_fake = "/content/gdrive/My Drive/img_retina_Kaggle_class_4_state_of_art_GAN/329/"
psnr_averages = []
for fake_image in os.listdir(directory_fake):
  PSNR_average = 0
  i = 0
  for real_image in os.listdir(directory_real_class_4):
    img_real = cv2.imread(directory_real_class_4 + real_image)
    img_fake = cv2.imread(directory_fake + fake_image)
    img_real = cv2.resize(img_real, (128, 128))
    img_fake = cv2.resize(img_fake, (128, 128))
    PSNR_none = PSNR(img_real, img_fake)
    PSNR_average += PSNR_none
    i+=1
  PSNR_average = PSNR_average/i
  psnr_averages.append(PSNR_average)
  #print(fake_image + " " + str(PSNR_average))
print(min(psnr_averages))
print(max(psnr_averages))

directory_real_class_4 = "/content/gdrive/My Drive/Kaggle/randomly selected preprocessed/class 2/"
directory_fake = "/content/gdrive/My Drive/img_retina_Kaggle_class_4_state_of_art_GAN/339/"
psnr_averages = []
for fake_image in os.listdir(directory_fake):
  PSNR_average = 0
  i = 0
  for real_image in os.listdir(directory_real_class_4):
    img_real = cv2.imread(directory_real_class_4 + real_image)
    img_fake = cv2.imread(directory_fake + fake_image)
    img_real = cv2.resize(img_real, (128, 128))
    img_fake = cv2.resize(img_fake, (128, 128))
    PSNR_none = PSNR(img_real, img_fake)
    PSNR_average += PSNR_none
    i+=1
  PSNR_average = PSNR_average/i
  psnr_averages.append(PSNR_average)
  #print(fake_image + " " + str(PSNR_average))
print(min(psnr_averages))
print(max(psnr_averages))

directory_real_class_4 = "/content/gdrive/My Drive/Kaggle/randomly selected preprocessed/class 2/"
directory_fake = "/content/gdrive/My Drive/img_retina_Kaggle_class_4_state_of_art_GAN/349/"
psnr_averages = []
for fake_image in os.listdir(directory_fake):
  PSNR_average = 0
  i = 0
  for real_image in os.listdir(directory_real_class_4):
    img_real = cv2.imread(directory_real_class_4 + real_image)
    img_fake = cv2.imread(directory_fake + fake_image)
    img_real = cv2.resize(img_real, (128, 128))
    img_fake = cv2.resize(img_fake, (128, 128))
    PSNR_none = PSNR(img_real, img_fake)
    PSNR_average += PSNR_none
    i+=1
  PSNR_average = PSNR_average/i
  psnr_averages.append(PSNR_average)
  #print(fake_image + " " + str(PSNR_average))
print(min(psnr_averages))
print(max(psnr_averages))

directory_real_class_4 = "/content/gdrive/My Drive/Kaggle/randomly selected preprocessed/class 2/"
directory_fake = "/content/gdrive/My Drive/img_retina_Kaggle_class_4_state_of_art_GAN/359/"
psnr_averages = []
for fake_image in os.listdir(directory_fake):
  PSNR_average = 0
  i = 0
  for real_image in os.listdir(directory_real_class_4):
    img_real = cv2.imread(directory_real_class_4 + real_image)
    img_fake = cv2.imread(directory_fake + fake_image)
    img_real = cv2.resize(img_real, (128, 128))
    img_fake = cv2.resize(img_fake, (128, 128))
    PSNR_none = PSNR(img_real, img_fake)
    PSNR_average += PSNR_none
    i+=1
  PSNR_average = PSNR_average/i
  psnr_averages.append(PSNR_average)
  #print(fake_image + " " + str(PSNR_average))
print(min(psnr_averages))
print(max(psnr_averages))

directory_real_class_4 = "/content/gdrive/My Drive/Kaggle/randomly selected preprocessed/class 2/"
directory_fake = "/content/gdrive/My Drive/img_retina_Kaggle_class_4_state_of_art_GAN/369/"
psnr_averages = []
for fake_image in os.listdir(directory_fake):
  PSNR_average = 0
  i = 0
  for real_image in os.listdir(directory_real_class_4):
    img_real = cv2.imread(directory_real_class_4 + real_image)
    img_fake = cv2.imread(directory_fake + fake_image)
    img_real = cv2.resize(img_real, (128, 128))
    img_fake = cv2.resize(img_fake, (128, 128))
    PSNR_none = PSNR(img_real, img_fake)
    PSNR_average += PSNR_none
    i+=1
  PSNR_average = PSNR_average/i
  psnr_averages.append(PSNR_average)
  #print(fake_image + " " + str(PSNR_average))
print(min(psnr_averages))
print(max(psnr_averages))

directory_real_class_4 = "/content/gdrive/My Drive/Kaggle/randomly selected preprocessed/class 2/"
directory_fake = "/content/gdrive/My Drive/img_retina_Kaggle_class_4_state_of_art_GAN/379/"
psnr_averages = []
for fake_image in os.listdir(directory_fake):
  PSNR_average = 0
  i = 0
  for real_image in os.listdir(directory_real_class_4):
    img_real = cv2.imread(directory_real_class_4 + real_image)
    img_fake = cv2.imread(directory_fake + fake_image)
    img_real = cv2.resize(img_real, (128, 128))
    img_fake = cv2.resize(img_fake, (128, 128))
    PSNR_none = PSNR(img_real, img_fake)
    PSNR_average += PSNR_none
    i+=1
  PSNR_average = PSNR_average/i
  psnr_averages.append(PSNR_average)
  #print(fake_image + " " + str(PSNR_average))
print(min(psnr_averages))
print(max(psnr_averages))

directory_real_class_4 = "/content/gdrive/My Drive/Kaggle/randomly selected preprocessed/class 2/"
directory_fake = "/content/gdrive/My Drive/img_retina_Kaggle_class_4_state_of_art_GAN/389/"
psnr_averages = []
for fake_image in os.listdir(directory_fake):
  PSNR_average = 0
  i = 0
  for real_image in os.listdir(directory_real_class_4):
    img_real = cv2.imread(directory_real_class_4 + real_image)
    img_fake = cv2.imread(directory_fake + fake_image)
    img_real = cv2.resize(img_real, (128, 128))
    img_fake = cv2.resize(img_fake, (128, 128))
    PSNR_none = PSNR(img_real, img_fake)
    PSNR_average += PSNR_none
    i+=1
  PSNR_average = PSNR_average/i
  psnr_averages.append(PSNR_average)
  #print(fake_image + " " + str(PSNR_average))
print(min(psnr_averages))
print(max(psnr_averages))

directory_real_class_4 = "/content/gdrive/My Drive/Kaggle/randomly selected preprocessed/class 2/"
directory_fake = "/content/gdrive/My Drive/img_retina_Kaggle_class_4_state_of_art_GAN/399/"
psnr_averages = []
for fake_image in os.listdir(directory_fake):
  PSNR_average = 0
  i = 0
  for real_image in os.listdir(directory_real_class_4):
    img_real = cv2.imread(directory_real_class_4 + real_image)
    img_fake = cv2.imread(directory_fake + fake_image)
    img_real = cv2.resize(img_real, (128, 128))
    img_fake = cv2.resize(img_fake, (128, 128))
    PSNR_none = PSNR(img_real, img_fake)
    PSNR_average += PSNR_none
    i+=1
  PSNR_average = PSNR_average/i
  psnr_averages.append(PSNR_average)
  #print(fake_image + " " + str(PSNR_average))
print(min(psnr_averages))
print(max(psnr_averages))

directory_real_class_4 = "/content/gdrive/My Drive/Kaggle/randomly selected preprocessed/class 2/"
directory_fake = "/content/gdrive/My Drive/img_retina_Kaggle_class_4_state_of_art_GAN/409/"
psnr_averages = []
for fake_image in os.listdir(directory_fake):
  PSNR_average = 0
  i = 0
  for real_image in os.listdir(directory_real_class_4):
    img_real = cv2.imread(directory_real_class_4 + real_image)
    img_fake = cv2.imread(directory_fake + fake_image)
    img_real = cv2.resize(img_real, (128, 128))
    img_fake = cv2.resize(img_fake, (128, 128))
    PSNR_none = PSNR(img_real, img_fake)
    PSNR_average += PSNR_none
    i+=1
  PSNR_average = PSNR_average/i
  psnr_averages.append(PSNR_average)
  #print(fake_image + " " + str(PSNR_average))
print(min(psnr_averages))
print(max(psnr_averages))

directory_real_class_4 = "/content/gdrive/My Drive/Kaggle/randomly selected preprocessed/class 2/"
directory_fake = "/content/gdrive/My Drive/img_retina_Kaggle_class_4_state_of_art_GAN/419/"
psnr_averages = []
for fake_image in os.listdir(directory_fake):
  PSNR_average = 0
  i = 0
  for real_image in os.listdir(directory_real_class_4):
    img_real = cv2.imread(directory_real_class_4 + real_image)
    img_fake = cv2.imread(directory_fake + fake_image)
    img_real = cv2.resize(img_real, (128, 128))
    img_fake = cv2.resize(img_fake, (128, 128))
    PSNR_none = PSNR(img_real, img_fake)
    PSNR_average += PSNR_none
    i+=1
  PSNR_average = PSNR_average/i
  psnr_averages.append(PSNR_average)
  #print(fake_image + " " + str(PSNR_average))
print(min(psnr_averages))
print(max(psnr_averages))

directory_real_class_4 = "/content/gdrive/My Drive/Kaggle/randomly selected preprocessed/class 2/"
directory_fake = "/content/gdrive/My Drive/img_retina_Kaggle_class_4_state_of_art_GAN/429/"
psnr_averages = []
for fake_image in os.listdir(directory_fake):
  PSNR_average = 0
  i = 0
  for real_image in os.listdir(directory_real_class_4):
    img_real = cv2.imread(directory_real_class_4 + real_image)
    img_fake = cv2.imread(directory_fake + fake_image)
    img_real = cv2.resize(img_real, (128, 128))
    img_fake = cv2.resize(img_fake, (128, 128))
    PSNR_none = PSNR(img_real, img_fake)
    PSNR_average += PSNR_none
    i+=1
  PSNR_average = PSNR_average/i
  psnr_averages.append(PSNR_average)
  #print(fake_image + " " + str(PSNR_average))
print(min(psnr_averages))
print(max(psnr_averages))

directory_real_class_4 = "/content/gdrive/My Drive/Kaggle/randomly selected preprocessed/class 2/"
directory_fake = "/content/gdrive/My Drive/img_retina_Kaggle_class_4_state_of_art_GAN/439/"
psnr_averages = []
for fake_image in os.listdir(directory_fake):
  PSNR_average = 0
  i = 0
  for real_image in os.listdir(directory_real_class_4):
    img_real = cv2.imread(directory_real_class_4 + real_image)
    img_fake = cv2.imread(directory_fake + fake_image)
    img_real = cv2.resize(img_real, (128, 128))
    img_fake = cv2.resize(img_fake, (128, 128))
    PSNR_none = PSNR(img_real, img_fake)
    PSNR_average += PSNR_none
    i+=1
  PSNR_average = PSNR_average/i
  psnr_averages.append(PSNR_average)
  #print(fake_image + " " + str(PSNR_average))
print(min(psnr_averages))
print(max(psnr_averages))

directory_real_class_4 = "/content/gdrive/My Drive/Kaggle/randomly selected preprocessed/class 2/"
directory_fake = "/content/gdrive/My Drive/img_retina_Kaggle_class_4_state_of_art_GAN/449/"
psnr_averages = []
for fake_image in os.listdir(directory_fake):
  PSNR_average = 0
  i = 0
  for real_image in os.listdir(directory_real_class_4):
    img_real = cv2.imread(directory_real_class_4 + real_image)
    img_fake = cv2.imread(directory_fake + fake_image)
    img_real = cv2.resize(img_real, (128, 128))
    img_fake = cv2.resize(img_fake, (128, 128))
    PSNR_none = PSNR(img_real, img_fake)
    PSNR_average += PSNR_none
    i+=1
  PSNR_average = PSNR_average/i
  psnr_averages.append(PSNR_average)
  #print(fake_image + " " + str(PSNR_average))
print(min(psnr_averages))
print(max(psnr_averages))

directory_real_class_4 = "/content/gdrive/My Drive/Kaggle/randomly selected preprocessed/class 2/"
directory_fake = "/content/gdrive/My Drive/img_retina_Kaggle_class_4_state_of_art_GAN/459/"
psnr_averages = []
for fake_image in os.listdir(directory_fake):
  PSNR_average = 0
  i = 0
  for real_image in os.listdir(directory_real_class_4):
    img_real = cv2.imread(directory_real_class_4 + real_image)
    img_fake = cv2.imread(directory_fake + fake_image)
    img_real = cv2.resize(img_real, (128, 128))
    img_fake = cv2.resize(img_fake, (128, 128))
    PSNR_none = PSNR(img_real, img_fake)
    PSNR_average += PSNR_none
    i+=1
  PSNR_average = PSNR_average/i
  psnr_averages.append(PSNR_average)
  #print(fake_image + " " + str(PSNR_average))
print(min(psnr_averages))
print(max(psnr_averages))

directory_real_class_4 = "/content/gdrive/My Drive/Kaggle/randomly selected preprocessed/class 2/"
directory_fake = "/content/gdrive/My Drive/img_retina_Kaggle_class_4_state_of_art_GAN/469/"
psnr_averages = []
for fake_image in os.listdir(directory_fake):
  PSNR_average = 0
  i = 0
  for real_image in os.listdir(directory_real_class_4):
    img_real = cv2.imread(directory_real_class_4 + real_image)
    img_fake = cv2.imread(directory_fake + fake_image)
    img_real = cv2.resize(img_real, (128, 128))
    img_fake = cv2.resize(img_fake, (128, 128))
    PSNR_none = PSNR(img_real, img_fake)
    PSNR_average += PSNR_none
    i+=1
  PSNR_average = PSNR_average/i
  psnr_averages.append(PSNR_average)
  #print(fake_image + " " + str(PSNR_average))
print(min(psnr_averages))
print(max(psnr_averages))

directory_real_class_4 = "/content/gdrive/My Drive/Kaggle/randomly selected preprocessed/class 2/"
directory_fake = "/content/gdrive/My Drive/img_retina_Kaggle_class_4_state_of_art_GAN/479/"
psnr_averages = []
for fake_image in os.listdir(directory_fake):
  PSNR_average = 0
  i = 0
  for real_image in os.listdir(directory_real_class_4):
    img_real = cv2.imread(directory_real_class_4 + real_image)
    img_fake = cv2.imread(directory_fake + fake_image)
    img_real = cv2.resize(img_real, (128, 128))
    img_fake = cv2.resize(img_fake, (128, 128))
    PSNR_none = PSNR(img_real, img_fake)
    PSNR_average += PSNR_none
    i+=1
  PSNR_average = PSNR_average/i
  psnr_averages.append(PSNR_average)
  #print(fake_image + " " + str(PSNR_average))
print(min(psnr_averages))
print(max(psnr_averages))

directory_real_class_4 = "/content/gdrive/My Drive/Kaggle/randomly selected preprocessed/class 2/"
directory_fake = "/content/gdrive/My Drive/img_retina_Kaggle_class_4_state_of_art_GAN/489/"
psnr_averages = []
for fake_image in os.listdir(directory_fake):
  PSNR_average = 0
  i = 0
  for real_image in os.listdir(directory_real_class_4):
    img_real = cv2.imread(directory_real_class_4 + real_image)
    img_fake = cv2.imread(directory_fake + fake_image)
    img_real = cv2.resize(img_real, (128, 128))
    img_fake = cv2.resize(img_fake, (128, 128))
    PSNR_none = PSNR(img_real, img_fake)
    PSNR_average += PSNR_none
    i+=1
  PSNR_average = PSNR_average/i
  psnr_averages.append(PSNR_average)
  #print(fake_image + " " + str(PSNR_average))
print(min(psnr_averages))
print(max(psnr_averages))

directory_real_class_4 = "/content/gdrive/My Drive/Kaggle/randomly selected preprocessed/class 2/"
directory_fake = "/content/gdrive/My Drive/img_retina_Kaggle_class_4_state_of_art_GAN/499/"
psnr_averages = []
for fake_image in os.listdir(directory_fake):
  PSNR_average = 0
  i = 0
  for real_image in os.listdir(directory_real_class_4):
    img_real = cv2.imread(directory_real_class_4 + real_image)
    img_fake = cv2.imread(directory_fake + fake_image)
    img_real = cv2.resize(img_real, (128, 128))
    img_fake = cv2.resize(img_fake, (128, 128))
    PSNR_none = PSNR(img_real, img_fake)
    PSNR_average += PSNR_none
    i+=1
  PSNR_average = PSNR_average/i
  psnr_averages.append(PSNR_average)
  #print(fake_image + " " + str(PSNR_average))
print(min(psnr_averages))
print(max(psnr_averages))