# -*- coding: utf-8 -*-
"""Calculate PSNR between fake cass 4 and real class 0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oWRDsPHZvKRFelyleSk5Ff8ij6GSDCGs
"""

from math import log10, sqrt
import cv2
import numpy as np
import os

from google.colab import drive
drive.mount('/content/gdrive')

def PSNR(original, to_compare_with):
    mse = np.mean((original - to_compare_with) ** 2)
    if(mse == 0):
        return 100
    max_pixel = 255.0
    psnr = 20 * log10(max_pixel / sqrt(mse))
    return psnr

directory_real_class_4 = "/content/gdrive/My Drive/Kaggle/randomly selected preprocessed/class 0/"
directory_fake = "/content/gdrive/My Drive/img_retina_Kaggle_class_4_state_of_art_GAN/9/"
PSNR_average = 0
i = 0
for real_image in os.listdir(directory_real_class_4):
  for fake_image in os.listdir(directory_fake):
    img_real = cv2.imread(directory_real_class_4 + real_image)
    img_fake = cv2.imread(directory_fake + fake_image)
    img_real = cv2.resize(img_real, (128, 128))
    img_fake = cv2.resize(img_fake, (128, 128))
    PSNR_none = PSNR(img_real, img_fake)
    PSNR_average += PSNR_none
    i+=1
    #print(i)
PSNR_average = PSNR_average/i
print("---------------")
print(PSNR_average)

directory_real_class_4 = "/content/gdrive/My Drive/Kaggle/randomly selected preprocessed/class 0/"
directory_fake = "/content/gdrive/My Drive/img_retina_Kaggle_class_4_state_of_art_GAN/19/"
PSNR_average = 0
i = 0
for real_image in os.listdir(directory_real_class_4):
  for fake_image in os.listdir(directory_fake):
    img_real = cv2.imread(directory_real_class_4 + real_image)
    img_fake = cv2.imread(directory_fake + fake_image)
    img_real = cv2.resize(img_real, (128, 128))
    img_fake = cv2.resize(img_fake, (128, 128))
    PSNR_none = PSNR(img_real, img_fake)
    PSNR_average += PSNR_none
    i+=1
    #print(i)
PSNR_average = PSNR_average/i
print("---------------")
print(PSNR_average)

directory_real_class_4 = "/content/gdrive/My Drive/Kaggle/randomly selected preprocessed/class 0/"
directory_fake = "/content/gdrive/My Drive/img_retina_Kaggle_class_4_state_of_art_GAN/29/"
PSNR_average = 0
i = 0
for real_image in os.listdir(directory_real_class_4):
  for fake_image in os.listdir(directory_fake):
    img_real = cv2.imread(directory_real_class_4 + real_image)
    img_fake = cv2.imread(directory_fake + fake_image)
    img_real = cv2.resize(img_real, (128, 128))
    img_fake = cv2.resize(img_fake, (128, 128))
    PSNR_none = PSNR(img_real, img_fake)
    PSNR_average += PSNR_none
    i+=1
    #print(i)
PSNR_average = PSNR_average/i
print("---------------")
print(PSNR_average)

directory_real_class_4 = "/content/gdrive/My Drive/Kaggle/randomly selected preprocessed/class 0/"
directory_fake = "/content/gdrive/My Drive/img_retina_Kaggle_class_4_state_of_art_GAN/39/"
PSNR_average = 0
i = 0
for real_image in os.listdir(directory_real_class_4):
  for fake_image in os.listdir(directory_fake):
    img_real = cv2.imread(directory_real_class_4 + real_image)
    img_fake = cv2.imread(directory_fake + fake_image)
    img_real = cv2.resize(img_real, (128, 128))
    img_fake = cv2.resize(img_fake, (128, 128))
    PSNR_none = PSNR(img_real, img_fake)
    PSNR_average += PSNR_none
    i+=1
    #print(i)
PSNR_average = PSNR_average/i
print("---------------")
print(PSNR_average)

directory_real_class_4 = "/content/gdrive/My Drive/Kaggle/randomly selected preprocessed/class 0/"
directory_fake = "/content/gdrive/My Drive/img_retina_Kaggle_class_4_state_of_art_GAN/49/"
PSNR_average = 0
i = 0
for real_image in os.listdir(directory_real_class_4):
  for fake_image in os.listdir(directory_fake):
    img_real = cv2.imread(directory_real_class_4 + real_image)
    img_fake = cv2.imread(directory_fake + fake_image)
    img_real = cv2.resize(img_real, (128, 128))
    img_fake = cv2.resize(img_fake, (128, 128))
    PSNR_none = PSNR(img_real, img_fake)
    PSNR_average += PSNR_none
    i+=1
    #print(i)
PSNR_average = PSNR_average/i
print("---------------")
print(PSNR_average)

directory_real_class_4 = "/content/gdrive/My Drive/Kaggle/randomly selected preprocessed/class 0/"
directory_fake = "/content/gdrive/My Drive/img_retina_Kaggle_class_4_state_of_art_GAN/59/"
PSNR_average = 0
i = 0
for real_image in os.listdir(directory_real_class_4):
  for fake_image in os.listdir(directory_fake):
    img_real = cv2.imread(directory_real_class_4 + real_image)
    img_fake = cv2.imread(directory_fake + fake_image)
    img_real = cv2.resize(img_real, (128, 128))
    img_fake = cv2.resize(img_fake, (128, 128))
    PSNR_none = PSNR(img_real, img_fake)
    PSNR_average += PSNR_none
    i+=1
    #print(i)
PSNR_average = PSNR_average/i
print("---------------")
print(PSNR_average)

directory_real_class_4 = "/content/gdrive/My Drive/Kaggle/randomly selected preprocessed/class 0/"
directory_fake = "/content/gdrive/My Drive/img_retina_Kaggle_class_4_state_of_art_GAN/69/"
PSNR_average = 0
i = 0
for real_image in os.listdir(directory_real_class_4):
  for fake_image in os.listdir(directory_fake):
    img_real = cv2.imread(directory_real_class_4 + real_image)
    img_fake = cv2.imread(directory_fake + fake_image)
    img_real = cv2.resize(img_real, (128, 128))
    img_fake = cv2.resize(img_fake, (128, 128))
    PSNR_none = PSNR(img_real, img_fake)
    PSNR_average += PSNR_none
    i+=1
    #print(i)
PSNR_average = PSNR_average/i
print("---------------")
print(PSNR_average)

directory_real_class_4 = "/content/gdrive/My Drive/Kaggle/randomly selected preprocessed/class 0/"
directory_fake = "/content/gdrive/My Drive/img_retina_Kaggle_class_4_state_of_art_GAN/79/"
PSNR_average = 0
i = 0
for real_image in os.listdir(directory_real_class_4):
  for fake_image in os.listdir(directory_fake):
    img_real = cv2.imread(directory_real_class_4 + real_image)
    img_fake = cv2.imread(directory_fake + fake_image)
    img_real = cv2.resize(img_real, (128, 128))
    img_fake = cv2.resize(img_fake, (128, 128))
    PSNR_none = PSNR(img_real, img_fake)
    PSNR_average += PSNR_none
    i+=1
    #print(i)
PSNR_average = PSNR_average/i
print("---------------")
print(PSNR_average)

directory_real_class_4 = "/content/gdrive/My Drive/Kaggle/randomly selected preprocessed/class 0/"
directory_fake = "/content/gdrive/My Drive/img_retina_Kaggle_class_4_state_of_art_GAN/89/"
PSNR_average = 0
i = 0
for real_image in os.listdir(directory_real_class_4):
  for fake_image in os.listdir(directory_fake):
    img_real = cv2.imread(directory_real_class_4 + real_image)
    img_fake = cv2.imread(directory_fake + fake_image)
    img_real = cv2.resize(img_real, (128, 128))
    img_fake = cv2.resize(img_fake, (128, 128))
    PSNR_none = PSNR(img_real, img_fake)
    PSNR_average += PSNR_none
    i+=1
    #print(i)
PSNR_average = PSNR_average/i
print("---------------")
print(PSNR_average)

directory_real_class_4 = "/content/gdrive/My Drive/Kaggle/randomly selected preprocessed/class 0/"
directory_fake = "/content/gdrive/My Drive/img_retina_Kaggle_class_4_state_of_art_GAN/99/"
PSNR_average = 0
i = 0
for real_image in os.listdir(directory_real_class_4):
  for fake_image in os.listdir(directory_fake):
    img_real = cv2.imread(directory_real_class_4 + real_image)
    img_fake = cv2.imread(directory_fake + fake_image)
    img_real = cv2.resize(img_real, (128, 128))
    img_fake = cv2.resize(img_fake, (128, 128))
    PSNR_none = PSNR(img_real, img_fake)
    PSNR_average += PSNR_none
    i+=1
    #print(i)
PSNR_average = PSNR_average/i
print("---------------")
print(PSNR_average)

directory_real_class_4 = "/content/gdrive/My Drive/Kaggle/randomly selected preprocessed/class 0/"
directory_fake = "/content/gdrive/My Drive/img_retina_Kaggle_class_4_state_of_art_GAN/109/"
PSNR_average = 0
i = 0
for real_image in os.listdir(directory_real_class_4):
  for fake_image in os.listdir(directory_fake):
    img_real = cv2.imread(directory_real_class_4 + real_image)
    img_fake = cv2.imread(directory_fake + fake_image)
    img_real = cv2.resize(img_real, (128, 128))
    img_fake = cv2.resize(img_fake, (128, 128))
    PSNR_none = PSNR(img_real, img_fake)
    PSNR_average += PSNR_none
    i+=1
    #print(i)
PSNR_average = PSNR_average/i
print("---------------")
print(PSNR_average)

directory_real_class_4 = "/content/gdrive/My Drive/Kaggle/randomly selected preprocessed/class 0/"
directory_fake = "/content/gdrive/My Drive/img_retina_Kaggle_class_4_state_of_art_GAN/119/"
PSNR_average = 0
i = 0
for real_image in os.listdir(directory_real_class_4):
  for fake_image in os.listdir(directory_fake):
    img_real = cv2.imread(directory_real_class_4 + real_image)
    img_fake = cv2.imread(directory_fake + fake_image)
    img_real = cv2.resize(img_real, (128, 128))
    img_fake = cv2.resize(img_fake, (128, 128))
    PSNR_none = PSNR(img_real, img_fake)
    PSNR_average += PSNR_none
    i+=1
    #print(i)
PSNR_average = PSNR_average/i
print("---------------")
print(PSNR_average)

directory_real_class_4 = "/content/gdrive/My Drive/Kaggle/randomly selected preprocessed/class 0/"
directory_fake = "/content/gdrive/My Drive/img_retina_Kaggle_class_4_state_of_art_GAN/129/"
PSNR_average = 0
i = 0
for real_image in os.listdir(directory_real_class_4):
  for fake_image in os.listdir(directory_fake):
    img_real = cv2.imread(directory_real_class_4 + real_image)
    img_fake = cv2.imread(directory_fake + fake_image)
    img_real = cv2.resize(img_real, (128, 128))
    img_fake = cv2.resize(img_fake, (128, 128))
    PSNR_none = PSNR(img_real, img_fake)
    PSNR_average += PSNR_none
    i+=1
    #print(i)
PSNR_average = PSNR_average/i
print("---------------")
print(PSNR_average)

directory_real_class_4 = "/content/gdrive/My Drive/Kaggle/randomly selected preprocessed/class 0/"
directory_fake = "/content/gdrive/My Drive/img_retina_Kaggle_class_4_state_of_art_GAN/139/"
PSNR_average = 0
i = 0
for real_image in os.listdir(directory_real_class_4):
  for fake_image in os.listdir(directory_fake):
    img_real = cv2.imread(directory_real_class_4 + real_image)
    img_fake = cv2.imread(directory_fake + fake_image)
    img_real = cv2.resize(img_real, (128, 128))
    img_fake = cv2.resize(img_fake, (128, 128))
    PSNR_none = PSNR(img_real, img_fake)
    PSNR_average += PSNR_none
    i+=1
    #print(i)
PSNR_average = PSNR_average/i
print("---------------")
print(PSNR_average)

directory_real_class_4 = "/content/gdrive/My Drive/Kaggle/randomly selected preprocessed/class 0/"
directory_fake = "/content/gdrive/My Drive/img_retina_Kaggle_class_4_state_of_art_GAN/149/"
PSNR_average = 0
i = 0
for real_image in os.listdir(directory_real_class_4):
  for fake_image in os.listdir(directory_fake):
    img_real = cv2.imread(directory_real_class_4 + real_image)
    img_fake = cv2.imread(directory_fake + fake_image)
    img_real = cv2.resize(img_real, (128, 128))
    img_fake = cv2.resize(img_fake, (128, 128))
    PSNR_none = PSNR(img_real, img_fake)
    PSNR_average += PSNR_none
    i+=1
    #print(i)
PSNR_average = PSNR_average/i
print("---------------")
print(PSNR_average)

directory_real_class_4 = "/content/gdrive/My Drive/Kaggle/randomly selected preprocessed/class 0/"
directory_fake = "/content/gdrive/My Drive/img_retina_Kaggle_class_4_state_of_art_GAN/159/"
PSNR_average = 0
i = 0
for real_image in os.listdir(directory_real_class_4):
  for fake_image in os.listdir(directory_fake):
    img_real = cv2.imread(directory_real_class_4 + real_image)
    img_fake = cv2.imread(directory_fake + fake_image)
    img_real = cv2.resize(img_real, (128, 128))
    img_fake = cv2.resize(img_fake, (128, 128))
    PSNR_none = PSNR(img_real, img_fake)
    PSNR_average += PSNR_none
    i+=1
    #print(i)
PSNR_average = PSNR_average/i
print("---------------")
print(PSNR_average)

directory_real_class_4 = "/content/gdrive/My Drive/Kaggle/randomly selected preprocessed/class 0/"
directory_fake = "/content/gdrive/My Drive/img_retina_Kaggle_class_4_state_of_art_GAN/169/"
PSNR_average = 0
i = 0
for real_image in os.listdir(directory_real_class_4):
  for fake_image in os.listdir(directory_fake):
    img_real = cv2.imread(directory_real_class_4 + real_image)
    img_fake = cv2.imread(directory_fake + fake_image)
    img_real = cv2.resize(img_real, (128, 128))
    img_fake = cv2.resize(img_fake, (128, 128))
    PSNR_none = PSNR(img_real, img_fake)
    PSNR_average += PSNR_none
    i+=1
    #print(i)
PSNR_average = PSNR_average/i
print("---------------")
print(PSNR_average)

directory_real_class_4 = "/content/gdrive/My Drive/Kaggle/randomly selected preprocessed/class 0/"
directory_fake = "/content/gdrive/My Drive/img_retina_Kaggle_class_4_state_of_art_GAN/179/"
PSNR_average = 0
i = 0
for real_image in os.listdir(directory_real_class_4):
  for fake_image in os.listdir(directory_fake):
    img_real = cv2.imread(directory_real_class_4 + real_image)
    img_fake = cv2.imread(directory_fake + fake_image)
    img_real = cv2.resize(img_real, (128, 128))
    img_fake = cv2.resize(img_fake, (128, 128))
    PSNR_none = PSNR(img_real, img_fake)
    PSNR_average += PSNR_none
    i+=1
    #print(i)
PSNR_average = PSNR_average/i
print("---------------")
print(PSNR_average)

directory_real_class_4 = "/content/gdrive/My Drive/Kaggle/randomly selected preprocessed/class 0/"
directory_fake = "/content/gdrive/My Drive/img_retina_Kaggle_class_4_state_of_art_GAN/189/"
PSNR_average = 0
i = 0
for real_image in os.listdir(directory_real_class_4):
  for fake_image in os.listdir(directory_fake):
    img_real = cv2.imread(directory_real_class_4 + real_image)
    img_fake = cv2.imread(directory_fake + fake_image)
    img_real = cv2.resize(img_real, (128, 128))
    img_fake = cv2.resize(img_fake, (128, 128))
    PSNR_none = PSNR(img_real, img_fake)
    PSNR_average += PSNR_none
    i+=1
    #print(i)
PSNR_average = PSNR_average/i
print("---------------")
print(PSNR_average)

directory_real_class_4 = "/content/gdrive/My Drive/Kaggle/randomly selected preprocessed/class 0/"
directory_fake = "/content/gdrive/My Drive/img_retina_Kaggle_class_4_state_of_art_GAN/199/"
PSNR_average = 0
i = 0
for real_image in os.listdir(directory_real_class_4):
  for fake_image in os.listdir(directory_fake):
    img_real = cv2.imread(directory_real_class_4 + real_image)
    img_fake = cv2.imread(directory_fake + fake_image)
    img_real = cv2.resize(img_real, (128, 128))
    img_fake = cv2.resize(img_fake, (128, 128))
    PSNR_none = PSNR(img_real, img_fake)
    PSNR_average += PSNR_none
    i+=1
    #print(i)
PSNR_average = PSNR_average/i
print("---------------")
print(PSNR_average)

directory_real_class_4 = "/content/gdrive/My Drive/Kaggle/randomly selected preprocessed/class 0/"
directory_fake = "/content/gdrive/My Drive/img_retina_Kaggle_class_4_state_of_art_GAN/209/"
PSNR_average = 0
i = 0
for real_image in os.listdir(directory_real_class_4):
  for fake_image in os.listdir(directory_fake):
    img_real = cv2.imread(directory_real_class_4 + real_image)
    img_fake = cv2.imread(directory_fake + fake_image)
    img_real = cv2.resize(img_real, (128, 128))
    img_fake = cv2.resize(img_fake, (128, 128))
    PSNR_none = PSNR(img_real, img_fake)
    PSNR_average += PSNR_none
    i+=1
    #print(i)
PSNR_average = PSNR_average/i
print("---------------")
print(PSNR_average)

directory_real_class_4 = "/content/gdrive/My Drive/Kaggle/randomly selected preprocessed/class 0/"
directory_fake = "/content/gdrive/My Drive/img_retina_Kaggle_class_4_state_of_art_GAN/219/"
PSNR_average = 0
i = 0
for real_image in os.listdir(directory_real_class_4):
  for fake_image in os.listdir(directory_fake):
    img_real = cv2.imread(directory_real_class_4 + real_image)
    img_fake = cv2.imread(directory_fake + fake_image)
    img_real = cv2.resize(img_real, (128, 128))
    img_fake = cv2.resize(img_fake, (128, 128))
    PSNR_none = PSNR(img_real, img_fake)
    PSNR_average += PSNR_none
    i+=1
    #print(i)
PSNR_average = PSNR_average/i
print("---------------")
print(PSNR_average)

directory_real_class_4 = "/content/gdrive/My Drive/Kaggle/randomly selected preprocessed/class 0/"
directory_fake = "/content/gdrive/My Drive/img_retina_Kaggle_class_4_state_of_art_GAN/229/"
PSNR_average = 0
i = 0
for real_image in os.listdir(directory_real_class_4):
  for fake_image in os.listdir(directory_fake):
    img_real = cv2.imread(directory_real_class_4 + real_image)
    img_fake = cv2.imread(directory_fake + fake_image)
    img_real = cv2.resize(img_real, (128, 128))
    img_fake = cv2.resize(img_fake, (128, 128))
    PSNR_none = PSNR(img_real, img_fake)
    PSNR_average += PSNR_none
    i+=1
    #print(i)
PSNR_average = PSNR_average/i
print("---------------")
print(PSNR_average)

directory_real_class_4 = "/content/gdrive/My Drive/Kaggle/randomly selected preprocessed/class 0/"
directory_fake = "/content/gdrive/My Drive/img_retina_Kaggle_class_4_state_of_art_GAN/239/"
PSNR_average = 0
i = 0
for real_image in os.listdir(directory_real_class_4):
  for fake_image in os.listdir(directory_fake):
    img_real = cv2.imread(directory_real_class_4 + real_image)
    img_fake = cv2.imread(directory_fake + fake_image)
    img_real = cv2.resize(img_real, (128, 128))
    img_fake = cv2.resize(img_fake, (128, 128))
    PSNR_none = PSNR(img_real, img_fake)
    PSNR_average += PSNR_none
    i+=1
    #print(i)
PSNR_average = PSNR_average/i
print("---------------")
print(PSNR_average)

directory_real_class_4 = "/content/gdrive/My Drive/Kaggle/randomly selected preprocessed/class 0/"
directory_fake = "/content/gdrive/My Drive/img_retina_Kaggle_class_4_state_of_art_GAN/249/"
PSNR_average = 0
i = 0
for real_image in os.listdir(directory_real_class_4):
  for fake_image in os.listdir(directory_fake):
    img_real = cv2.imread(directory_real_class_4 + real_image)
    img_fake = cv2.imread(directory_fake + fake_image)
    img_real = cv2.resize(img_real, (128, 128))
    img_fake = cv2.resize(img_fake, (128, 128))
    PSNR_none = PSNR(img_real, img_fake)
    PSNR_average += PSNR_none
    i+=1
    #print(i)
PSNR_average = PSNR_average/i
print("---------------")
print(PSNR_average)

directory_real_class_4 = "/content/gdrive/My Drive/Kaggle/randomly selected preprocessed/class 0/"
directory_fake = "/content/gdrive/My Drive/img_retina_Kaggle_class_4_state_of_art_GAN/259/"
PSNR_average = 0
i = 0
for real_image in os.listdir(directory_real_class_4):
  for fake_image in os.listdir(directory_fake):
    img_real = cv2.imread(directory_real_class_4 + real_image)
    img_fake = cv2.imread(directory_fake + fake_image)
    img_real = cv2.resize(img_real, (128, 128))
    img_fake = cv2.resize(img_fake, (128, 128))
    PSNR_none = PSNR(img_real, img_fake)
    PSNR_average += PSNR_none
    i+=1
    #print(i)
PSNR_average = PSNR_average/i
print("---------------")
print(PSNR_average)

directory_real_class_4 = "/content/gdrive/My Drive/Kaggle/randomly selected preprocessed/class 0/"
directory_fake = "/content/gdrive/My Drive/img_retina_Kaggle_class_4_state_of_art_GAN/269/"
PSNR_average = 0
i = 0
for real_image in os.listdir(directory_real_class_4):
  for fake_image in os.listdir(directory_fake):
    img_real = cv2.imread(directory_real_class_4 + real_image)
    img_fake = cv2.imread(directory_fake + fake_image)
    img_real = cv2.resize(img_real, (128, 128))
    img_fake = cv2.resize(img_fake, (128, 128))
    PSNR_none = PSNR(img_real, img_fake)
    PSNR_average += PSNR_none
    i+=1
    #print(i)
PSNR_average = PSNR_average/i
print("---------------")
print(PSNR_average)

directory_real_class_4 = "/content/gdrive/My Drive/Kaggle/randomly selected preprocessed/class 0/"
directory_fake = "/content/gdrive/My Drive/img_retina_Kaggle_class_4_state_of_art_GAN/279/"
PSNR_average = 0
i = 0
for real_image in os.listdir(directory_real_class_4):
  for fake_image in os.listdir(directory_fake):
    img_real = cv2.imread(directory_real_class_4 + real_image)
    img_fake = cv2.imread(directory_fake + fake_image)
    img_real = cv2.resize(img_real, (128, 128))
    img_fake = cv2.resize(img_fake, (128, 128))
    PSNR_none = PSNR(img_real, img_fake)
    PSNR_average += PSNR_none
    i+=1
    #print(i)
PSNR_average = PSNR_average/i
print("---------------")
print(PSNR_average)

directory_real_class_4 = "/content/gdrive/My Drive/Kaggle/randomly selected preprocessed/class 0/"
directory_fake = "/content/gdrive/My Drive/img_retina_Kaggle_class_4_state_of_art_GAN/289/"
PSNR_average = 0
i = 0
for real_image in os.listdir(directory_real_class_4):
  for fake_image in os.listdir(directory_fake):
    img_real = cv2.imread(directory_real_class_4 + real_image)
    img_fake = cv2.imread(directory_fake + fake_image)
    img_real = cv2.resize(img_real, (128, 128))
    img_fake = cv2.resize(img_fake, (128, 128))
    PSNR_none = PSNR(img_real, img_fake)
    PSNR_average += PSNR_none
    i+=1
    #print(i)
PSNR_average = PSNR_average/i
print("---------------")
print(PSNR_average)

directory_real_class_4 = "/content/gdrive/My Drive/Kaggle/randomly selected preprocessed/class 0/"
directory_fake = "/content/gdrive/My Drive/img_retina_Kaggle_class_4_state_of_art_GAN/299/"
PSNR_average = 0
i = 0
for real_image in os.listdir(directory_real_class_4):
  for fake_image in os.listdir(directory_fake):
    img_real = cv2.imread(directory_real_class_4 + real_image)
    img_fake = cv2.imread(directory_fake + fake_image)
    img_real = cv2.resize(img_real, (128, 128))
    img_fake = cv2.resize(img_fake, (128, 128))
    PSNR_none = PSNR(img_real, img_fake)
    PSNR_average += PSNR_none
    i+=1
    #print(i)
PSNR_average = PSNR_average/i
print("---------------")
print(PSNR_average)

directory_real_class_4 = "/content/gdrive/My Drive/Kaggle/randomly selected preprocessed/class 0/"
directory_fake = "/content/gdrive/My Drive/img_retina_Kaggle_class_4_state_of_art_GAN/309/"
PSNR_average = 0
i = 0
for real_image in os.listdir(directory_real_class_4):
  for fake_image in os.listdir(directory_fake):
    img_real = cv2.imread(directory_real_class_4 + real_image)
    img_fake = cv2.imread(directory_fake + fake_image)
    img_real = cv2.resize(img_real, (128, 128))
    img_fake = cv2.resize(img_fake, (128, 128))
    PSNR_none = PSNR(img_real, img_fake)
    PSNR_average += PSNR_none
    i+=1
    #print(i)
PSNR_average = PSNR_average/i
print("---------------")
print(PSNR_average)

directory_real_class_4 = "/content/gdrive/My Drive/Kaggle/randomly selected preprocessed/class 0/"
directory_fake = "/content/gdrive/My Drive/img_retina_Kaggle_class_4_state_of_art_GAN/319/"
PSNR_average = 0
i = 0
for real_image in os.listdir(directory_real_class_4):
  for fake_image in os.listdir(directory_fake):
    img_real = cv2.imread(directory_real_class_4 + real_image)
    img_fake = cv2.imread(directory_fake + fake_image)
    img_real = cv2.resize(img_real, (128, 128))
    img_fake = cv2.resize(img_fake, (128, 128))
    PSNR_none = PSNR(img_real, img_fake)
    PSNR_average += PSNR_none
    i+=1
    #print(i)
PSNR_average = PSNR_average/i
print("---------------")
print(PSNR_average)

directory_real_class_4 = "/content/gdrive/My Drive/Kaggle/randomly selected preprocessed/class 0/"
directory_fake = "/content/gdrive/My Drive/img_retina_Kaggle_class_4_state_of_art_GAN/329/"
PSNR_average = 0
i = 0
for real_image in os.listdir(directory_real_class_4):
  for fake_image in os.listdir(directory_fake):
    img_real = cv2.imread(directory_real_class_4 + real_image)
    img_fake = cv2.imread(directory_fake + fake_image)
    img_real = cv2.resize(img_real, (128, 128))
    img_fake = cv2.resize(img_fake, (128, 128))
    PSNR_none = PSNR(img_real, img_fake)
    PSNR_average += PSNR_none
    i+=1
    #print(i)
PSNR_average = PSNR_average/i
print("---------------")
print(PSNR_average)

directory_real_class_4 = "/content/gdrive/My Drive/Kaggle/randomly selected preprocessed/class 0/"
directory_fake = "/content/gdrive/My Drive/img_retina_Kaggle_class_4_state_of_art_GAN/339/"
PSNR_average = 0
i = 0
for real_image in os.listdir(directory_real_class_4):
  for fake_image in os.listdir(directory_fake):
    img_real = cv2.imread(directory_real_class_4 + real_image)
    img_fake = cv2.imread(directory_fake + fake_image)
    img_real = cv2.resize(img_real, (128, 128))
    img_fake = cv2.resize(img_fake, (128, 128))
    PSNR_none = PSNR(img_real, img_fake)
    PSNR_average += PSNR_none
    i+=1
    #print(i)
PSNR_average = PSNR_average/i
print("---------------")
print(PSNR_average)

directory_real_class_4 = "/content/gdrive/My Drive/Kaggle/randomly selected preprocessed/class 0/"
directory_fake = "/content/gdrive/My Drive/img_retina_Kaggle_class_4_state_of_art_GAN/349/"
PSNR_average = 0
i = 0
for real_image in os.listdir(directory_real_class_4):
  for fake_image in os.listdir(directory_fake):
    img_real = cv2.imread(directory_real_class_4 + real_image)
    img_fake = cv2.imread(directory_fake + fake_image)
    img_real = cv2.resize(img_real, (128, 128))
    img_fake = cv2.resize(img_fake, (128, 128))
    PSNR_none = PSNR(img_real, img_fake)
    PSNR_average += PSNR_none
    i+=1
    #print(i)
PSNR_average = PSNR_average/i
print("---------------")
print(PSNR_average)

directory_real_class_4 = "/content/gdrive/My Drive/Kaggle/randomly selected preprocessed/class 0/"
directory_fake = "/content/gdrive/My Drive/img_retina_Kaggle_class_4_state_of_art_GAN/359/"
PSNR_average = 0
i = 0
for real_image in os.listdir(directory_real_class_4):
  for fake_image in os.listdir(directory_fake):
    img_real = cv2.imread(directory_real_class_4 + real_image)
    img_fake = cv2.imread(directory_fake + fake_image)
    img_real = cv2.resize(img_real, (128, 128))
    img_fake = cv2.resize(img_fake, (128, 128))
    PSNR_none = PSNR(img_real, img_fake)
    PSNR_average += PSNR_none
    i+=1
    #print(i)
PSNR_average = PSNR_average/i
print("---------------")
print(PSNR_average)

directory_real_class_4 = "/content/gdrive/My Drive/Kaggle/randomly selected preprocessed/class 0/"
directory_fake = "/content/gdrive/My Drive/img_retina_Kaggle_class_4_state_of_art_GAN/369/"
PSNR_average = 0
i = 0
for real_image in os.listdir(directory_real_class_4):
  for fake_image in os.listdir(directory_fake):
    img_real = cv2.imread(directory_real_class_4 + real_image)
    img_fake = cv2.imread(directory_fake + fake_image)
    img_real = cv2.resize(img_real, (128, 128))
    img_fake = cv2.resize(img_fake, (128, 128))
    PSNR_none = PSNR(img_real, img_fake)
    PSNR_average += PSNR_none
    i+=1
    #print(i)
PSNR_average = PSNR_average/i
print("---------------")
print(PSNR_average)

directory_real_class_4 = "/content/gdrive/My Drive/Kaggle/randomly selected preprocessed/class 0/"
directory_fake = "/content/gdrive/My Drive/img_retina_Kaggle_class_4_state_of_art_GAN/379/"
PSNR_average = 0
i = 0
for real_image in os.listdir(directory_real_class_4):
  for fake_image in os.listdir(directory_fake):
    img_real = cv2.imread(directory_real_class_4 + real_image)
    img_fake = cv2.imread(directory_fake + fake_image)
    img_real = cv2.resize(img_real, (128, 128))
    img_fake = cv2.resize(img_fake, (128, 128))
    PSNR_none = PSNR(img_real, img_fake)
    PSNR_average += PSNR_none
    i+=1
    #print(i)
PSNR_average = PSNR_average/i
print("---------------")
print(PSNR_average)

directory_real_class_4 = "/content/gdrive/My Drive/Kaggle/randomly selected preprocessed/class 0/"
directory_fake = "/content/gdrive/My Drive/img_retina_Kaggle_class_4_state_of_art_GAN/389/"
PSNR_average = 0
i = 0
for real_image in os.listdir(directory_real_class_4):
  for fake_image in os.listdir(directory_fake):
    img_real = cv2.imread(directory_real_class_4 + real_image)
    img_fake = cv2.imread(directory_fake + fake_image)
    img_real = cv2.resize(img_real, (128, 128))
    img_fake = cv2.resize(img_fake, (128, 128))
    PSNR_none = PSNR(img_real, img_fake)
    PSNR_average += PSNR_none
    i+=1
    #print(i)
PSNR_average = PSNR_average/i
print("---------------")
print(PSNR_average)

directory_real_class_4 = "/content/gdrive/My Drive/Kaggle/randomly selected preprocessed/class 0/"
directory_fake = "/content/gdrive/My Drive/img_retina_Kaggle_class_4_state_of_art_GAN/399/"
PSNR_average = 0
i = 0
for real_image in os.listdir(directory_real_class_4):
  for fake_image in os.listdir(directory_fake):
    img_real = cv2.imread(directory_real_class_4 + real_image)
    img_fake = cv2.imread(directory_fake + fake_image)
    img_real = cv2.resize(img_real, (128, 128))
    img_fake = cv2.resize(img_fake, (128, 128))
    PSNR_none = PSNR(img_real, img_fake)
    PSNR_average += PSNR_none
    i+=1
    #print(i)
PSNR_average = PSNR_average/i
print("---------------")
print(PSNR_average)

directory_real_class_4 = "/content/gdrive/My Drive/Kaggle/randomly selected preprocessed/class 0/"
directory_fake = "/content/gdrive/My Drive/img_retina_Kaggle_class_4_state_of_art_GAN/409/"
PSNR_average = 0
i = 0
for real_image in os.listdir(directory_real_class_4):
  for fake_image in os.listdir(directory_fake):
    img_real = cv2.imread(directory_real_class_4 + real_image)
    img_fake = cv2.imread(directory_fake + fake_image)
    img_real = cv2.resize(img_real, (128, 128))
    img_fake = cv2.resize(img_fake, (128, 128))
    PSNR_none = PSNR(img_real, img_fake)
    PSNR_average += PSNR_none
    i+=1
    #print(i)
PSNR_average = PSNR_average/i
print("---------------")
print(PSNR_average)

directory_real_class_4 = "/content/gdrive/My Drive/Kaggle/randomly selected preprocessed/class 0/"
directory_fake = "/content/gdrive/My Drive/img_retina_Kaggle_class_4_state_of_art_GAN/419/"
PSNR_average = 0
i = 0
for real_image in os.listdir(directory_real_class_4):
  for fake_image in os.listdir(directory_fake):
    img_real = cv2.imread(directory_real_class_4 + real_image)
    img_fake = cv2.imread(directory_fake + fake_image)
    img_real = cv2.resize(img_real, (128, 128))
    img_fake = cv2.resize(img_fake, (128, 128))
    PSNR_none = PSNR(img_real, img_fake)
    PSNR_average += PSNR_none
    i+=1
    #print(i)
PSNR_average = PSNR_average/i
print("---------------")
print(PSNR_average)

directory_real_class_4 = "/content/gdrive/My Drive/Kaggle/randomly selected preprocessed/class 0/"
directory_fake = "/content/gdrive/My Drive/img_retina_Kaggle_class_4_state_of_art_GAN/429/"
PSNR_average = 0
i = 0
for real_image in os.listdir(directory_real_class_4):
  for fake_image in os.listdir(directory_fake):
    img_real = cv2.imread(directory_real_class_4 + real_image)
    img_fake = cv2.imread(directory_fake + fake_image)
    img_real = cv2.resize(img_real, (128, 128))
    img_fake = cv2.resize(img_fake, (128, 128))
    PSNR_none = PSNR(img_real, img_fake)
    PSNR_average += PSNR_none
    i+=1
    #print(i)
PSNR_average = PSNR_average/i
print("---------------")
print(PSNR_average)

directory_real_class_4 = "/content/gdrive/My Drive/Kaggle/randomly selected preprocessed/class 0/"
directory_fake = "/content/gdrive/My Drive/img_retina_Kaggle_class_4_state_of_art_GAN/439/"
PSNR_average = 0
i = 0
for real_image in os.listdir(directory_real_class_4):
  for fake_image in os.listdir(directory_fake):
    img_real = cv2.imread(directory_real_class_4 + real_image)
    img_fake = cv2.imread(directory_fake + fake_image)
    img_real = cv2.resize(img_real, (128, 128))
    img_fake = cv2.resize(img_fake, (128, 128))
    PSNR_none = PSNR(img_real, img_fake)
    PSNR_average += PSNR_none
    i+=1
    #print(i)
PSNR_average = PSNR_average/i
print("---------------")
print(PSNR_average)

directory_real_class_4 = "/content/gdrive/My Drive/Kaggle/randomly selected preprocessed/class 0/"
directory_fake = "/content/gdrive/My Drive/img_retina_Kaggle_class_4_state_of_art_GAN/449/"
PSNR_average = 0
i = 0
for real_image in os.listdir(directory_real_class_4):
  for fake_image in os.listdir(directory_fake):
    img_real = cv2.imread(directory_real_class_4 + real_image)
    img_fake = cv2.imread(directory_fake + fake_image)
    img_real = cv2.resize(img_real, (128, 128))
    img_fake = cv2.resize(img_fake, (128, 128))
    PSNR_none = PSNR(img_real, img_fake)
    PSNR_average += PSNR_none
    i+=1
    #print(i)
PSNR_average = PSNR_average/i
print("---------------")
print(PSNR_average)

directory_real_class_4 = "/content/gdrive/My Drive/Kaggle/randomly selected preprocessed/class 0/"
directory_fake = "/content/gdrive/My Drive/img_retina_Kaggle_class_4_state_of_art_GAN/459/"
PSNR_average = 0
i = 0
for real_image in os.listdir(directory_real_class_4):
  for fake_image in os.listdir(directory_fake):
    img_real = cv2.imread(directory_real_class_4 + real_image)
    img_fake = cv2.imread(directory_fake + fake_image)
    img_real = cv2.resize(img_real, (128, 128))
    img_fake = cv2.resize(img_fake, (128, 128))
    PSNR_none = PSNR(img_real, img_fake)
    PSNR_average += PSNR_none
    i+=1
    #print(i)
PSNR_average = PSNR_average/i
print("---------------")
print(PSNR_average)

directory_real_class_4 = "/content/gdrive/My Drive/Kaggle/randomly selected preprocessed/class 0/"
directory_fake = "/content/gdrive/My Drive/img_retina_Kaggle_class_4_state_of_art_GAN/469/"
PSNR_average = 0
i = 0
for real_image in os.listdir(directory_real_class_4):
  for fake_image in os.listdir(directory_fake):
    img_real = cv2.imread(directory_real_class_4 + real_image)
    img_fake = cv2.imread(directory_fake + fake_image)
    img_real = cv2.resize(img_real, (128, 128))
    img_fake = cv2.resize(img_fake, (128, 128))
    PSNR_none = PSNR(img_real, img_fake)
    PSNR_average += PSNR_none
    i+=1
    #print(i)
PSNR_average = PSNR_average/i
print("---------------")
print(PSNR_average)

directory_real_class_4 = "/content/gdrive/My Drive/Kaggle/randomly selected preprocessed/class 0/"
directory_fake = "/content/gdrive/My Drive/img_retina_Kaggle_class_4_state_of_art_GAN/479/"
PSNR_average = 0
i = 0
for real_image in os.listdir(directory_real_class_4):
  for fake_image in os.listdir(directory_fake):
    img_real = cv2.imread(directory_real_class_4 + real_image)
    img_fake = cv2.imread(directory_fake + fake_image)
    img_real = cv2.resize(img_real, (128, 128))
    img_fake = cv2.resize(img_fake, (128, 128))
    PSNR_none = PSNR(img_real, img_fake)
    PSNR_average += PSNR_none
    i+=1
    #print(i)
PSNR_average = PSNR_average/i
print("---------------")
print(PSNR_average)

directory_real_class_4 = "/content/gdrive/My Drive/Kaggle/randomly selected preprocessed/class 0/"
directory_fake = "/content/gdrive/My Drive/img_retina_Kaggle_class_4_state_of_art_GAN/489/"
PSNR_average = 0
i = 0
for real_image in os.listdir(directory_real_class_4):
  for fake_image in os.listdir(directory_fake):
    img_real = cv2.imread(directory_real_class_4 + real_image)
    img_fake = cv2.imread(directory_fake + fake_image)
    img_real = cv2.resize(img_real, (128, 128))
    img_fake = cv2.resize(img_fake, (128, 128))
    PSNR_none = PSNR(img_real, img_fake)
    PSNR_average += PSNR_none
    i+=1
    #print(i)
PSNR_average = PSNR_average/i
print("---------------")
print(PSNR_average)

directory_real_class_4 = "/content/gdrive/My Drive/Kaggle/randomly selected preprocessed/class 0/"
directory_fake = "/content/gdrive/My Drive/img_retina_Kaggle_class_4_state_of_art_GAN/499/"
PSNR_average = 0
i = 0
for real_image in os.listdir(directory_real_class_4):
  for fake_image in os.listdir(directory_fake):
    img_real = cv2.imread(directory_real_class_4 + real_image)
    img_fake = cv2.imread(directory_fake + fake_image)
    img_real = cv2.resize(img_real, (128, 128))
    img_fake = cv2.resize(img_fake, (128, 128))
    PSNR_none = PSNR(img_real, img_fake)
    PSNR_average += PSNR_none
    i+=1
    #print(i)
PSNR_average = PSNR_average/i
print("---------------")
print(PSNR_average)



