# -*- coding: utf-8 -*-
"""Select random images of every class.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZqaAOt1-nmA78B6fofwYPN9YlAR4eE62
"""

import random
import shutil
import pandas as pd
import os

from google.colab import drive
drive.mount('/content/gdrive', force_remount=True)



#find all images of class 0 2nd time
data = pd.read_csv("/content/gdrive/My Drive/Kaggle/Groundtruths/KaggleTrainLabels.csv")
data_class_zero = data[data["level"] == 0]
image_names = data_class_zero["image"]
image_names = list(image_names)
print(image_names[0])

randomlist = random.sample(range(0, 25810), 100)
print(randomlist)

for random_number in randomlist:
  image_to_move = image_names[random_number] + ".jpeg"
  original = r'/content/gdrive/My Drive/Kaggle/training preprocessed/' + image_to_move
  target = r'/content/gdrive/My Drive/Kaggle/randomly selected preprocessed 2/class 0/' + image_to_move
  shutil.copyfile(original, target)

#find all images of class 0 2nd time
data = pd.read_csv("/content/gdrive/My Drive/Kaggle/Groundtruths/KaggleTrainLabels.csv")
data_class_zero = data[data["level"] == 1]
image_names = data_class_zero["image"]
image_names = list(image_names)
print(image_names[0])

randomlist = random.sample(range(0, 2443), 100)
print(randomlist)

for random_number in randomlist:
  image_to_move = image_names[random_number] + ".jpeg"
  original = r'/content/gdrive/My Drive/Kaggle/training preprocessed/' + image_to_move
  target = r'/content/gdrive/My Drive/Kaggle/randomly selected preprocessed 2/class 1/' + image_to_move
  shutil.copyfile(original, target)

#find all images of class 0 2nd time
data = pd.read_csv("/content/gdrive/My Drive/Kaggle/Groundtruths/KaggleTrainLabels.csv")
data_class_zero = data[data["level"] == 2]
image_names = data_class_zero["image"]
image_names = list(image_names)
print(image_names[0])

randomlist = random.sample(range(0, 5292), 100)
print(randomlist)

for random_number in randomlist:
  image_to_move = image_names[random_number] + ".jpeg"
  original = r'/content/gdrive/My Drive/Kaggle/training preprocessed/' + image_to_move
  target = r'/content/gdrive/My Drive/Kaggle/randomly selected preprocessed 2/class 2/' + image_to_move
  shutil.copyfile(original, target)

#find all images of class 0 2nd time
data = pd.read_csv("/content/gdrive/My Drive/Kaggle/Groundtruths/KaggleTrainLabels.csv")
data_class_zero = data[data["level"] == 3]
image_names = data_class_zero["image"]
image_names = list(image_names)
print(image_names[0])

randomlist = random.sample(range(0, 873), 100)
print(randomlist)

for random_number in randomlist:
  image_to_move = image_names[random_number] + ".jpeg"
  original = r'/content/gdrive/My Drive/Kaggle/training preprocessed/' + image_to_move
  target = r'/content/gdrive/My Drive/Kaggle/randomly selected preprocessed 2/class 3/' + image_to_move
  shutil.copyfile(original, target)

#find all images of class 0 2nd time
data = pd.read_csv("/content/gdrive/My Drive/Kaggle/Groundtruths/KaggleTrainLabels.csv")
data_class_zero = data[data["level"] == 4]
image_names = data_class_zero["image"]
image_names = list(image_names)
print(image_names[0])

randomlist = random.sample(range(0, 708), 100)
print(randomlist)

for random_number in randomlist:
  image_to_move = image_names[random_number] + ".jpeg"
  original = r'/content/gdrive/My Drive/Kaggle/training preprocessed/' + image_to_move
  target = r'/content/gdrive/My Drive/Kaggle/randomly selected preprocessed 2/class 4/' + image_to_move
  shutil.copyfile(original, target)



#find all images of class 0 2nd time
data = pd.read_csv("/content/gdrive/My Drive/Kaggle/Groundtruths/KaggleTrainLabels.csv")
data_class_zero = data[data["level"] == 0]
image_names = data_class_zero["image"]
image_names = list(image_names)
print(image_names[0])

randomlist = random.sample(range(0, 25810), 100)
print(randomlist)

for random_number in randomlist:
  image_to_move = image_names[random_number] + ".jpeg"
  original = r'/content/gdrive/My Drive/Kaggle/training preprocessed/' + image_to_move
  target = r'/content/gdrive/My Drive/Kaggle/randomly selected preprocessed 3/class 0/' + image_to_move
  shutil.copyfile(original, target)

#find all images of class 0 2nd time
data = pd.read_csv("/content/gdrive/My Drive/Kaggle/Groundtruths/KaggleTrainLabels.csv")
data_class_zero = data[data["level"] == 1]
image_names = data_class_zero["image"]
image_names = list(image_names)
print(image_names[0])

randomlist = random.sample(range(0, 2443), 100)
print(randomlist)

for random_number in randomlist:
  image_to_move = image_names[random_number] + ".jpeg"
  original = r'/content/gdrive/My Drive/Kaggle/training preprocessed/' + image_to_move
  target = r'/content/gdrive/My Drive/Kaggle/randomly selected preprocessed 3/class 1/' + image_to_move
  shutil.copyfile(original, target)

#find all images of class 0 2nd time
data = pd.read_csv("/content/gdrive/My Drive/Kaggle/Groundtruths/KaggleTrainLabels.csv")
data_class_zero = data[data["level"] == 2]
image_names = data_class_zero["image"]
image_names = list(image_names)
print(image_names[0])

randomlist = random.sample(range(0, 5292), 100)
print(randomlist)

for random_number in randomlist:
  image_to_move = image_names[random_number] + ".jpeg"
  original = r'/content/gdrive/My Drive/Kaggle/training preprocessed/' + image_to_move
  target = r'/content/gdrive/My Drive/Kaggle/randomly selected preprocessed 3/class 2/' + image_to_move
  shutil.copyfile(original, target)

#find all images of class 0 2nd time
data = pd.read_csv("/content/gdrive/My Drive/Kaggle/Groundtruths/KaggleTrainLabels.csv")
data_class_zero = data[data["level"] == 3]
image_names = data_class_zero["image"]
image_names = list(image_names)
print(image_names[0])

randomlist = random.sample(range(0, 873), 100)
print(randomlist)

for random_number in randomlist:
  image_to_move = image_names[random_number] + ".jpeg"
  original = r'/content/gdrive/My Drive/Kaggle/training preprocessed/' + image_to_move
  target = r'/content/gdrive/My Drive/Kaggle/randomly selected preprocessed 3/class 3/' + image_to_move
  shutil.copyfile(original, target)

#find all images of class 0 2nd time
data = pd.read_csv("/content/gdrive/My Drive/Kaggle/Groundtruths/KaggleTrainLabels.csv")
data_class_zero = data[data["level"] == 4]
image_names = data_class_zero["image"]
image_names = list(image_names)
print(image_names[0])

randomlist = random.sample(range(0, 708), 100)
print(randomlist)

for random_number in randomlist:
  image_to_move = image_names[random_number] + ".jpeg"
  original = r'/content/gdrive/My Drive/Kaggle/training preprocessed/' + image_to_move
  target = r'/content/gdrive/My Drive/Kaggle/randomly selected preprocessed 3/class 4/' + image_to_move
  shutil.copyfile(original, target)

#find all images of class 0 2nd time
data = pd.read_csv("/content/gdrive/My Drive/Kaggle/Groundtruths/KaggleTrainLabels.csv")
data_class_zero = data[data["level"] == 0]
image_names = data_class_zero["image"]
image_names = list(image_names)
print(image_names[0])

randomlist = random.sample(range(0, 25810), 100)
print(randomlist)

for random_number in randomlist:
  image_to_move = image_names[random_number] + ".jpeg"
  original = r'/content/gdrive/My Drive/Kaggle/training preprocessed/' + image_to_move
  target = r'/content/gdrive/My Drive/Kaggle/randomly selected preprocessed 4/class 0/' + image_to_move
  shutil.copyfile(original, target)

#find all images of class 0 2nd time
data = pd.read_csv("/content/gdrive/My Drive/Kaggle/Groundtruths/KaggleTrainLabels.csv")
data_class_zero = data[data["level"] == 1]
image_names = data_class_zero["image"]
image_names = list(image_names)
print(image_names[0])

randomlist = random.sample(range(0, 2443), 100)
print(randomlist)

for random_number in randomlist:
  image_to_move = image_names[random_number] + ".jpeg"
  original = r'/content/gdrive/My Drive/Kaggle/training preprocessed/' + image_to_move
  target = r'/content/gdrive/My Drive/Kaggle/randomly selected preprocessed 4/class 1/' + image_to_move
  shutil.copyfile(original, target)

#find all images of class 0 2nd time
data = pd.read_csv("/content/gdrive/My Drive/Kaggle/Groundtruths/KaggleTrainLabels.csv")
data_class_zero = data[data["level"] == 2]
image_names = data_class_zero["image"]
image_names = list(image_names)
print(image_names[0])

randomlist = random.sample(range(0, 5292), 100)
print(randomlist)

for random_number in randomlist:
  image_to_move = image_names[random_number] + ".jpeg"
  original = r'/content/gdrive/My Drive/Kaggle/training preprocessed/' + image_to_move
  target = r'/content/gdrive/My Drive/Kaggle/randomly selected preprocessed 4/class 2/' + image_to_move
  shutil.copyfile(original, target)

#find all images of class 0 2nd time
data = pd.read_csv("/content/gdrive/My Drive/Kaggle/Groundtruths/KaggleTrainLabels.csv")
data_class_zero = data[data["level"] == 3]
image_names = data_class_zero["image"]
image_names = list(image_names)
print(image_names[0])

randomlist = random.sample(range(0, 873), 100)
print(randomlist)

for random_number in randomlist:
  image_to_move = image_names[random_number] + ".jpeg"
  original = r'/content/gdrive/My Drive/Kaggle/training preprocessed/' + image_to_move
  target = r'/content/gdrive/My Drive/Kaggle/randomly selected preprocessed 4/class 3/' + image_to_move
  shutil.copyfile(original, target)

#find all images of class 0 2nd time
data = pd.read_csv("/content/gdrive/My Drive/Kaggle/Groundtruths/KaggleTrainLabels.csv")
data_class_zero = data[data["level"] == 4]
image_names = data_class_zero["image"]
image_names = list(image_names)
print(image_names[0])

randomlist = random.sample(range(0, 708), 100)
print(randomlist)

for random_number in randomlist:
  image_to_move = image_names[random_number] + ".jpeg"
  original = r'/content/gdrive/My Drive/Kaggle/training preprocessed/' + image_to_move
  target = r'/content/gdrive/My Drive/Kaggle/randomly selected preprocessed 4/class 4/' + image_to_move
  shutil.copyfile(original, target)





folder_preprocessed = r'/content/gdrive/My Drive/Kaggle/randomly selected preprocessed/class 4/'
for image_to_move in os.listdir(folder_preprocessed):
  #image_to_move = image_names[random_number] + ".jpeg"
  original = r'/content/gdrive/My Drive/Kaggle/training/' + image_to_move
  target = r'/content/gdrive/My Drive/Kaggle/randomly selected not preprocessed/class 4/' + image_to_move
  shutil.copyfile(original, target)

#find all images of class 0
data = pd.read_csv("/content/gdrive/My Drive/Kaggle/Groundtruths/KaggleTrainLabels.csv")
data_class_zero = data[data["level"] == 4]
image_names = data_class_zero["image"]
image_names = list(image_names)
print(image_names[0])

randomlist = random.sample(range(0, 708), 708)
print(randomlist)

for random_number in randomlist:
  image_to_move = image_names[random_number] + ".jpeg"
  original = r'/content/gdrive/My Drive/Kaggle/training preprocessed/' + image_to_move
  target = r'/content/gdrive/My Drive/Kaggle/randomly selected training preprocessed/' + image_to_move
  shutil.copyfile(original, target)